[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[terminal.shell]
program = "/bin/zsh"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black = "#000000"
white = "#ffffff"
red = "#ff0000"
green = "#00ff00"
blue = "#0000ff"
yellow = "#ffff00"
magenta = "#ff00ff"
cyan = "#800080"
